<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Orassans</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>   
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*-*" />
    <PackageReference Include="Lib.Harmony" ExcludeAssets="runtime">
            <Version>2.4.2</Version>
        </PackageReference>	
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AlienRace">
      <HintPath>..\..\..\..\..\Users\conse\Desktop\!Reference Assemblies\AlienRace.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>